# incus-pet — per-app incus container CLI ("pet PaaS").
#
# Subcommands: deploy, list, rm.
#
# Container port is fixed at 8080 (declared by ../container.nix); the
# host-side <listen-ip>:<host-port> is unique per app and stored in
# container metadata so re-deploys are flagless. See ./README.md for
# the network model and operator flow.
#
# Marshaling-flake-as-module design (vs. nixos-rebuild --target-host):
# the per-deploy state-dir flake exposes ONLY `nixosModules.default`
# (combined container essentials + app's nixosModules.incus +
# operator-key overlay). The CLI picks nixpkgs at build time (pinned
# to nixos-25.11, matching the LXC image baseline) and assembles the
# nixosSystem via `nix build --impure --expr`. Closure copy + activation
# happen via `nix copy --to ssh://…` + ssh-driven
# switch-to-configuration. Lets us dodge unstable nixpkgs regressions
# (e.g. the dbus-broker reload stall) without touching the marshaling
# flake's shape.
{ writeShellApplication
, nix
, openssh
, jq
, coreutils
, gnused
, ...
}:
let
  # The container essentials module — baked in at build time as a store
  # path. The marshaling flake imports it directly so we don't have to
  # turn the incus/ tree into a flake.
  essentialsModule = ../container.nix;
in
writeShellApplication {
  name = "incus-pet";

  runtimeInputs = [ nix openssh jq coreutils gnused ];

  meta.description = "Deploy a NixOS service flake into a per-app incus container (pet PaaS).";

  text = ''
    set -euo pipefail

    ESSENTIALS_MODULE='${essentialsModule}'
    CONTAINER_PORT=8080
    STATE_ROOT="''${XDG_STATE_HOME:-$HOME/.local/state}/incus-pet"
    INCUS_IMAGE="images:nixos/25.11"
    # Pinned to stable to match the LXC image baseline. Unstable triggers
    # a dbus-broker reload stall in switch-to-configuration (~Jul 2026
    # systemd/dbus-broker regression).
    NIXPKGS_REF="github:nixos/nixpkgs/nixos-25.11"

    log() { printf '[incus-pet] %s\n' "$*" >&2; }
    die() { log "error: $*"; exit 1; }

    usage() {
      cat >&2 <<'EOF'
    Usage:
      incus-pet deploy <flake-ref> [<name>] [--port N] [--listen IP]
      incus-pet list
      incus-pet rm <name>

    Environment:
      INCUS_PET_LISTEN   default listen IP for the host-side proxy device
                         (overridden by --listen)

    First-time `deploy` requires --port; subsequent deploys read it from
    container metadata. See README.md for the network model.
    EOF
      exit 2
    }

    # ----- helpers -----

    ensure_incus() {
      command -v incus >/dev/null 2>&1 || die "incus not in PATH (host needs the incus daemon)"
    }

    operator_pubkey() {
      # The key root@<container> will trust. Try ed25519 then rsa.
      local f
      for f in "$HOME/.ssh/id_ed25519.pub" "$HOME/.ssh/id_rsa.pub"; do
        if [ -r "$f" ]; then cat "$f"; return; fi
      done
      die "no ssh public key found at ~/.ssh/id_ed25519.pub or ~/.ssh/id_rsa.pub"
    }

    container_exists() {
      incus info "$1" >/dev/null 2>&1
    }

    container_ipv4() {
      # Poll briefly — fresh containers take a second to get DHCP.
      local name="$1" tries=0 ip=""
      while [ "$tries" -lt 30 ]; do
        ip=$(incus list "$name" --format=json 2>/dev/null \
              | jq -r '.[0].state.network.eth0.addresses[]? | select(.family=="inet") | .address' \
              | head -n1 || true)
        if [ -n "$ip" ] && [ "$ip" != "null" ]; then
          printf '%s\n' "$ip"; return 0
        fi
        sleep 1
        tries=$((tries + 1))
      done
      die "container $name did not get an IPv4 address within 30s"
    }

    config_get() {
      # Echo empty string if the key is unset (incus returns empty + 0).
      incus config get "$1" "$2" 2>/dev/null || true
    }

    write_marshaling_flake() {
      # Per-deploy state-dir flake. Exposes ONLY nixosModules.default —
      # the CLI assembles the full nixosSystem at build time, picking
      # nixpkgs (so we can pin stable to dodge unstable regressions and
      # not bake the choice into per-deploy state).
      local flake_ref="$1" pubkey="$2"
      local dir="$STATE_ROOT/$3"  # caller-chosen subdir (probe or real name)
      mkdir -p "$dir"

      # Copy the essentials module into the marshaling flake dir as
      # ./container.nix and import it via relative path — keeps the
      # generated flake pure-evaluable (pure-eval forbids absolute
      # /nix/store imports not declared as flake inputs).
      cp -f "$ESSENTIALS_MODULE" "$dir/container.nix"

      cat > "$dir/flake.nix" <<EOF
    # Generated by incus-pet — do not edit. Re-run \`incus-pet deploy\` to refresh.
    {
      inputs.target.url = "$flake_ref";
      outputs = { target, ... }: {
        nixosModules.default = { ... }: {
          imports = [
            ./container.nix
            target.nixosModules.incus
          ];
          users.users.root.openssh.authorizedKeys.keys = [
            "$pubkey"
          ];
        };
      };
    }
    EOF
      printf '%s\n' "$dir"
    }

    precheck_target_flake() {
      local flake_ref="$1"
      if ! nix eval "$flake_ref#nixosModules.incus" --apply 'm: true' >/dev/null 2>&1; then
        die "flake $flake_ref does not expose nixosModules.incus; see SKILL.md Branch C for how to add the contract"
      fi
    }

    # Boilerplate that assembles the full nixosSystem on demand. Pinned
    # nixpkgs (NIXPKGS_REF) is fetched via builtins.getFlake; --impure
    # is required because builtins.getFlake on a URL isn't
    # pure-evaluable. The marshaling flake is loaded by absolute store
    # path so the operator's machine doesn't re-fetch it.
    sys_expr() {
      local dir="$1"
      printf 'let
        marshaling = builtins.getFlake "path:%s";
        nixpkgs = builtins.getFlake "%s";
      in nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [ marshaling.nixosModules.default ];
      }' "$dir" "$NIXPKGS_REF"
    }

    eval_config_attr() {
      local dir="$1" attr="$2"
      nix eval --raw --impure --expr "($(sys_expr "$dir")).config.$attr"
    }

    build_toplevel() {
      local dir="$1"
      nix build --print-out-paths --no-link --impure --expr \
        "($(sys_expr "$dir")).config.system.build.toplevel"
    }

    bootstrap_container() {
      # The official NixOS incus image already runs sshd via systemd
      # socket activation on port 22; the only thing we need to add is
      # the operator's pubkey to root's authorized_keys (for interactive
      # ssh debugging — the deploy path uses `incus exec`, not ssh).
      # Idempotent — `tee` overwrites, so a rotated key gets picked up
      # on next deploy.
      local name="$1" pubkey="$2"
      log "ensuring authorized_keys on $name"
      incus exec "$name" -- mkdir -p /root/.ssh
      incus exec "$name" -- chmod 700 /root/.ssh
      printf '%s\n' "$pubkey" | incus exec "$name" -- tee /root/.ssh/authorized_keys >/dev/null
      incus exec "$name" -- chmod 600 /root/.ssh/authorized_keys
    }

    # Mount the host's /nix/store into the container as read-only —
    # `shift=true` idmaps host UIDs into the unprivileged container.
    # Idempotent; takes effect on next container start. With this in
    # place, every container shares the host's /nix/store on disk —
    # zero duplication of nixpkgs closures across containers.
    ensure_nix_store_mount() {
      local name="$1"
      if incus config device show "$name" 2>/dev/null | grep -q '^nix-store:'; then
        return 0
      fi
      log "adding shared /nix/store mount on $name (host's store, read-only)"
      incus config device add "$name" nix-store disk \
        source=/nix/store \
        path=/nix/store \
        readonly=true \
        shift=true
    }

    # Pin the toplevel against host-side GC. The container's nix DB
    # doesn't know about the path (it lives behind the shared mount),
    # so without this the host could nix-collect-garbage the running
    # system out from under the container. `nix-store --add-root
    # --indirect` creates an indirect root: a user-writable symlink
    # (in our state dir, no sudo) plus a tracked entry in
    # /nix/var/nix/gcroots/auto/. Idempotent; overwrites prior.
    register_host_gcroot() {
      local name="$1" toplevel="$2"
      local link="$STATE_ROOT/$name/system"
      mkdir -p "$STATE_ROOT/$name"
      nix-store --add-root "$link" --indirect --realise "$toplevel" >/dev/null
    }

    wire_proxy_device() {
      local name="$1" listen="$2" host_port="$3"
      local devname="web"

      if incus config device show "$name" 2>/dev/null | grep -q "^$devname:"; then
        log "refreshing proxy device $devname on $name → $listen:$host_port"
        incus config device set "$name" "$devname" \
          listen="tcp:$listen:$host_port" \
          connect="tcp:127.0.0.1:$CONTAINER_PORT"
      else
        log "adding proxy device $devname on $name → $listen:$host_port"
        incus config device add "$name" "$devname" proxy \
          listen="tcp:$listen:$host_port" \
          connect="tcp:127.0.0.1:$CONTAINER_PORT"
      fi
    }

    # ----- subcommands -----

    cmd_deploy() {
      local flake_ref="" name="" port="" listen=""

      [ $# -ge 1 ] || usage
      flake_ref="$1"; shift

      # Optional positional name (anything that doesn't start with '-').
      if [ $# -ge 1 ] && [ "''${1#-}" = "$1" ]; then
        name="$1"; shift
      fi

      while [ $# -gt 0 ]; do
        case "$1" in
          --port)   port="$2"; shift 2 ;;
          --listen) listen="$2"; shift 2 ;;
          *) die "unknown flag: $1" ;;
        esac
      done

      ensure_incus

      # Normalize `.` to an absolute path so nix flake commands work
      # from anywhere downstream.
      if [ "$flake_ref" = "." ]; then
        flake_ref="path:$(pwd)"
      fi

      precheck_target_flake "$flake_ref"

      local pubkey
      pubkey=$(operator_pubkey)

      # We need the hostname to know the container name, but the hostname
      # lives in the evaluated config — which means we need to write the
      # marshaling flake first. If --name wasn't passed, use a temporary
      # placeholder; we'll re-evaluate after.
      local tentative_name="''${name:-_probe}"
      local dir
      dir=$(write_marshaling_flake "$flake_ref" "$pubkey" "$tentative_name")

      log "locking marshaling flake at $dir"
      # `nix flake update` (not `lock`) so every deploy bumps the target
      # input to the current tip of its ref (otherwise re-running `deploy
      # github:srid/anywhen` would stay pinned at the first commit we
      # saw). `--refresh` bypasses nix's fetcher cache so the resolution
      # is fresh, not a 5-min-stale entry.
      ( cd "$dir" && nix flake update --refresh )

      if [ -z "$name" ]; then
        name=$(eval_config_attr "$dir" "incus.container.hostname")
        log "container name from flake: $name"
        # Re-emit the marshaling flake under the real name so the
        # state-dir matches what `incus-pet list` shows.
        rm -rf "$STATE_ROOT/_probe"
        dir=$(write_marshaling_flake "$flake_ref" "$pubkey" "$name")
        # `nix flake update` (not `lock`) so every deploy bumps the target
      # input to the current tip of its ref (otherwise re-running `deploy
      # github:srid/anywhen` would stay pinned at the first commit we
      # saw). `--refresh` bypasses nix's fetcher cache so the resolution
      # is fresh, not a 5-min-stale entry.
      ( cd "$dir" && nix flake update --refresh )
      fi

      # Resolve host port (CLI flag > container metadata > error).
      if [ -z "$port" ]; then
        if container_exists "$name"; then
          port=$(config_get "$name" user.incus-pet.host-port)
        fi
        [ -n "$port" ] || die "first deploy of $name needs --port N (host-side port)"
      fi

      # Resolve listen IP (CLI flag > env > container metadata > 0.0.0.0).
      if [ -z "$listen" ]; then
        listen="''${INCUS_PET_LISTEN:-}"
      fi
      if [ -z "$listen" ] && container_exists "$name"; then
        listen=$(config_get "$name" user.incus-pet.listen)
      fi
      : "''${listen:=0.0.0.0}"

      # Ensure container exists.
      if ! container_exists "$name"; then
        log "launching container $name from $INCUS_IMAGE"
        incus launch "$INCUS_IMAGE" "$name" -c security.nesting=true
      fi

      local ip
      ip=$(container_ipv4 "$name")
      log "container $name has ipv4 $ip"

      bootstrap_container "$name" "$pubkey"

      log "building toplevel (pinned $NIXPKGS_REF)"
      local toplevel
      toplevel=$(build_toplevel "$dir")
      log "toplevel: $toplevel"

      log "pinning host gcroot for $name → $toplevel"
      register_host_gcroot "$name" "$toplevel"

      # Update the container's system profile FIRST (while it can still
      # see its own /nix/store), then add the shared-mount device if
      # missing, then restart so the new init picks up via the shared
      # mount. Order matters: if we added the mount before updating
      # the profile, the container's existing /sbin/init -> old toplevel
      # would point at a path masked by the mount and the restart would
      # fail.
      log "setting system profile on $name → $toplevel"
      incus exec "$name" -- ln -sfn "$toplevel" /nix/var/nix/profiles/system
      # The NixOS LXC image hard-links /sbin/init to the image's own
      # toplevel; re-pointing it through the profile symlink is what
      # makes "update profile + restart" actually pick up the new
      # toplevel's init (which sets up /etc, runs activation, then
      # execs systemd). NixOS's switch-to-configuration normally does
      # this — we have to do it ourselves since we skip s-t-c.
      # Idempotent across deploys.
      incus exec "$name" -- ln -sfn /nix/var/nix/profiles/system/init /sbin/init

      ensure_nix_store_mount "$name"

      log "restarting $name to boot via shared /nix/store"
      incus restart "$name"

      ip=$(container_ipv4 "$name")
      log "$name back up at $ip"

      # Persist host-port + listen IP for next deploy. The `key=value`
      # form is required since incus 6.x; the space-separated form is
      # deprecated and warns.
      incus config set "$name" "user.incus-pet.host-port=$port"
      incus config set "$name" "user.incus-pet.listen=$listen"
      incus config set "$name" "user.incus-pet.flake-ref=$flake_ref"

      wire_proxy_device "$name" "$listen" "$port"

      log "done: $name exposed on $listen:$port → container:8080"
    }

    cmd_list() {
      ensure_incus
      printf '%-20s %-50s %-25s %-10s\n' "NAME" "FLAKE" "EXPOSED" "STATUS"
      incus list --format=json | jq -r '.[] | select(.config["user.incus-pet.flake-ref"]) |
        [
          .name,
          .config["user.incus-pet.flake-ref"],
          (.config["user.incus-pet.listen"] + ":" + .config["user.incus-pet.host-port"]),
          .status
        ] | @tsv' | while IFS=$'\t' read -r n f e s; do
          printf '%-20s %-50s %-25s %-10s\n' "$n" "$f" "$e" "$s"
        done
    }

    cmd_rm() {
      ensure_incus
      [ $# -eq 1 ] || die "rm takes exactly one argument: the container name"
      local name="$1"
      log "stopping + deleting container $name"
      incus stop  "$name" --force 2>/dev/null || true
      incus delete "$name" 2>/dev/null || true
      rm -rf "''${STATE_ROOT:?}/$name"
      log "removed $name"
    }

    # ----- dispatch -----

    [ $# -ge 1 ] || usage
    sub="$1"; shift
    case "$sub" in
      deploy) cmd_deploy "$@" ;;
      list)   cmd_list   "$@" ;;
      rm)     cmd_rm     "$@" ;;
      -h|--help) usage ;;
      *) usage ;;
    esac
  '';
}
