
default:
    @just --list

# Run `agenix -e <file>` 
edit FILE:
    # bash -c 'agenix -e {{ FILE }} -i <(op read "op://Private/id_ed25519/private key")'
    agenix -e {{ FILE }} -i ~/.ssh/agenix

rekey:
    # bash -c 'agenix -r -i <(op read "op://Private/id_ed25519/private key")'
    agenix -r -i ~/.ssh/agenix